# Can spatial fisheries data improve assessment of stock status? {#sec-discussion}

The Tasmanian high-resolution spatial fisheries data collection program is highly cost-effective given the scope and scale of the information the program delivers. Spatial fisheries data derived from GPS logger programs provide multiple benefits for determining stock status in spatially structured abalone fisheries:

1.  provision of a more responsive measure of effort in the form of dive polygon area,

2.  identification of discrete reef systems as an improvement on within Spatial Assessment Unit spatial structure,

3.  through a temporal index of productivity (reported in an earlier milestone), and,

4.  provision of capacity to quantify the extent of reef used each year, and among consecutive years.

## Space is a better measure of effort than time

Area as a measure of effort in diver fisheries appears to offer greater sensitivity to stock changes and is less affected by hyperstability than time as a measure of effort. Passive GPS and Depth data logging technology capture dive time and dive area with greater precision than estimated daily dive effort by divers. Even when we have greater precision in capturing fishing effort in the form of dive time with depth data loggers, area however appears to be a better measure of effort to assess performance of the fishery, and therefore stock status. In essence, using both Area and Time as measure of effort, we are able to see the cross-over from when search time dominates the dive to when handling time is the limiting factor and search time is minimal.

The findings that catch rates based on diving time are subject to hyperstability are not evidence that CPUE (effort as *Time*) is a inaccurate measure of fishery performance as many would argue. This project merely confirms hyperstability is present at both high and low stock levels. Where *Time* is the only measure of effort available, Harvest Strategies can still effectively utilise CPUE as a performance measure, with simple adjustments such that as CPUE deviates from historical median catch rates, outcomes should be increasingly conservative, and when CPUE approaches historic high levels, outcomes can be more optimistic. However, it appears that the level of hyperstability is not entirely symmetrical, thus caution is advised when adjusting HS outcomes at the very high end of the scale.

## Explicit inclusion of dive location in catch rate standardisation

Abalone fisheries are well known for being highly variable, both in terms of fishery dynamics, biology and productivity, at local scales. Largely this comes from 'Fisher Ecological Knowledge' or 'Local Knowledge' [@anuchiracheeva2003; @hall2007; @hall2009; @nguyen2019], and has rarely been quantified through a data collection and analysis process. In @sec-chapter3 we illustrated that daily catch rates, can be highly variable, either as mean daily catch rates, or smoothed with a moving window average of 5, 20, or 30 days. As most catch rate standardisations account for season and fisher identity, one remaining predictor that had not been previously examined was the dive location as a primary driver of high variation in mean daily catch rate within a reporting area. Inclusion of spatial location as a term in the catch rate standardisations however, had negligible impact on predicted mean annual catch rate. Comparisons of models with and without spatial terms are rather difficult to compare directly through common methods such as R\^2 or AIC. The tools for spatial mixed effect models are still under rapid development, as are the diagnostic procedures and methods for comparison with non-spatial models. This project has touched on these methods, and is an area for future activity, although largely that will be to determine the extent of the *noise* captured by the model, but also in terms of spatial predictions to visualise usage of reef systems over times.

As abalone stocks decline, and eventually rebuild, fleet movement and individual diver choices on where to fish will signal important information in the depletion and recovery process. With hard copy logbook reporting, we are unable to determine whether a stock declines or stock recovery is homogeneous across an SAU, or whether there is significant spatial structure in changes that occur. This is particularly important where once important fishing grounds fail to recover, or recover more slowly. Traditionally information on this question is provided by fishers, although fishers rarely fish everywhere and may not always be aware of all activity in a particular area, and is this prone to gaps in knowledge (although that may no always be acknowledged). The GPS data logger program provides critical detail on where and to what extent components of a fishery change, and the rate at which they change. The investigation of fleet dynamics is an important new direction to better inform managers on the spatial structure of recovery [@ofarrell2017].

## Feasibility of spatial data for stock status

Tasmania now has a 12 year time-series of GPS and Depth logger data, covering on average around \~90% of fishing activity in the Tasmanian abalone fishery. For states with a shorter or fractured time-series, area-based metrics can still provide valuable insights on the trend of fishery performance by examining relative change from the time-series start-year, as deviations from time-based trends are evident after three to four years. data investigations (not included in this report) also suggests that the dive polygon based spatia performance measures can be informative at lower levels of fishery coverage. While an adequate time-series is being acquired from which to directly determine reference points for area based catch rates, an interim measure could be to fit a model between time and area, and predicted area based TRPs and LRPs from the more extensive time based catch rate data set.

Scales at which abalone fisheries are managed, are necessarily larger than the scale at which the fishery might be assessed. Total Allowable Commercial Catch (TACC) is often set at larger geographical scales such as fishery Zones, with effort management undertaken at within-zone scale in Spatial Assessment Units (Spatial Management Units, Fishery Areas). At still smaller scales, catch (but not necessarily catch rates) can vary widely. Of concern during a declining phase of a fishery is that smaller sections of coastline are abandoned, and there may be delays before those areas are re-integrated to the fishery (e.g. [@fig-sdm-trends-cl]). Thus catch rates at an SAU level may only represent the more productive and resilient sections of the coastline, and without access to the spatial detail of the fishery provided by GPS logger programs, the assumption will (incorrectly) be that the entire SAU is displaying the same trend. Most abalone fishery assessment processes as well as the Status of Australian Fish Stocks (SAFS) program are victim to the complications of Dynamic Pool assumptions @mundy2023. Many of the Dynamic Pool assumptions required by integrated assessment models are equally applicable to the calculation of mean annual catch rate, and, their interpretation. Regardless of whether catch rates utilise area or time as a measure of effort, catch rates are an index of local abundance at the time of fishing. Further, they are an index of what was taken and not what remains, and not representative of the entire stock. Access to spatial fisheries data partially solves this dilemma by providing the ability to examine fishing effort at relevant scales, either by inclusion of within SAU terms in catch rate standardisations (@sec-chapter3), or by examining the dynamic of fishing activity in the 1 Hectare hexagon grid layers (@sec-chapter5, @sec-chapter6, @sec-chapter7).

## Utility of logbook catch rate data for stock status

Docket or Logbook based catch and effort data remain valuable to the determination of stock status of abalone fisheries. This is with the caveat that fishing time reported in mandatory Docket book systems is reported accurately, as found for the Tasmanian abalone fishery (@sec-chapter1). Docket book data is free, and there is a long time-series of data available for all abalone fisheries. Providing that harvest strategies include appropriate precautionary settings when relying on Docket book catch rate data, there is no reason to stop relying on this valuable data source. The Tasmanian abalone Empirical Harvest Strategy achieves this by using an asymmetric control rule, which is more conservative as a fishery declines below the catch rate Target Reference Point compared to a rebuilding fishery which is above the TRP.

## Further work

The investigation of spatial mixed effect models in this study was limited and focused on the impact of including location on the annual mean catch rate. Further work is required to better understand the mechanics of these random spatial terms, and how best to utilise these tools to examine the spatio-temporal dynamic in our dive fishery. More work is required in this space to better understand to what extent mixed effect spatial linear models are capturing the variability in man daily catch rates (@sec-chapter3), and, whether they assist by providing greater confidence in the mean estimates provided.

Documenting and quantifying fleet dynamics remains a relatively untouched challenge. Tasmania Divers are paid a dive rate per Kilogram of abalone caught, and not by time. Unless other economic or weather factors come into play, there is a strong incentive for them to move on from areas where catch achieved by hour of effort declines below the individuals threshold. This may manifest in divers moving multiple times during a day, or, not returning to that fishing ground in the near future. Its this latter behaviour that will provide much greater insight to the status of stocks at appropriate spatial scales, and at scales smaller than SAUs.

## Recommendations

1.  Catch per Unit Area (CPUA) to be included as part of the catch rate analysis in the Tasmanian Fishery Assessment.
