# Introduction {#sec-intro .unnumbered}

Abalone stock status assessment is intrinsically difficult because stocks are typically spatially structured, utilise small vessels, target sedentary species, and are prone to serial depletion. Fisheries with these characteristics have been termed S-fisheries by Orensanz et al [-@orensanz2005]. Larval dispersal in the Blacklip Abalone *Haliotis rubra* is highly localised adding an additional spatial complexity. Obtaining representative biological data (growth, recruitment, mortality, emigration etc.) remains cost-prohibitive because abalone stocks are across extensive coastlines with substantial spatial structuring, requiring large numbers of sampling locations to capture the extent of variability. Local productivity of Blacklip is largely dependent on local abundance of reproductive individuals, and recovery from localised depletion is reliant on the remnant population as few external recruits will arrive to assist with population recovery [@miller2009]. All of these features present significant challenges when assessing stock status.

Determining 'global' stock status requires some knowledge of the collective status of local populations within a stock. Accurately accounting for local dynamics (recruitment, growth, mortality) remains a challenge for model based abalone fishery assessments because it is unlikely that all local populations in a stock will share a global parameter set [see @mundy2023 for a more extensive discussion]. Abalone assessments in many jurisdictions rely heavily on commercial catch-per-unit-effort (CPUE) data utlising fisher returns of catch and effort. Some jurisdictions have maintained a Fishery Independent Survey program, which can provide valuable performance measures in those jurisdictions. These programs are costly, and difficult to maintain representative coverage of the fished area. Given the micro-stock structure of abalone fisheries, use of fishery-dependent data to determine stock status is problematic because catch-rates are applicable only to the local population fished and are not indicative of 'global' stock levels [@parma2003]. When there are sufficient fishing events, time-series of sample parameters (mean, distribution shape) appear to be a useful indicator of fishery performance sufficient to make Total Allowable Commercial Catch (TACC) decisions. However, without data on the spatial extent of the fishery and how the area of reef utilised by the fishery varies through time, it remains uncertain whether CPUE can provide a meaningful indicator of overall stock biomass, changes in fishing mortality that might indicate increasing levels of over fishing, or the effectiveness of management interventions. For this reason substantial effort has been invested in the development of spatial indicators, and theoretically, fine-scale fishery-dependent spatial data could be used in the development of a 'global' stock status indicator for abalone fisheries.

The introduction of the Status of Australian Fish Stocks (SAFS) process is generally considered to be an excellent initiative. However, the common reporting template is based on equilibrium concepts such as current biomass relative to unfished biomass (B~0~), and relies on fisheries conforming to Dynamic Pool assumptions, which includes an assumption of a single homogeneous stock. Sedentary and sessile target species are unlikely to conform Dynamic Pool concepts [@seijo2004], and this is particularly applicable to abalone fisheries. The issue of lack of adherence to Dynamic Pool assumptions is an area both abalone scientists and abalone fishery managers have avoided, noting the challenges of factoring this understanding into both assessment and management of abalone fisheries. The lack of consideration in abalone and similar fisheries of just what a catch-rate indicator means in terms of stock status has created a significant stumbling block for scientists attempting to classify their fisheries as Sustainable, Depleting, Recovering, or Depleted. Collectively, our attempts to find a solution to the key issue - determining when a fishery has crossed a threshold from one category to another - have created tension, confusion, stress, and high levels of frustration across industry, management, research and FRDC.

Fishery-dependent data remain an important component of harvest control rules in Australian and New Zealand abalone fisheries (primarily catch-rates as Kg/Hr). However, with abalone, stable catch-rates may not indicate stable biomass and/or stable density. Catch-rates are frequently criticised because the effort (diving time) needed to take a quantity of catch may be influenced by density independent factors such as conditions at the time of fishing, experience, and the ability of fishers to adjust their fishing strategy to maintain catch rates (diver behaviour driven hyperstability). While there are many issues with the assumption that CPUE is a reliable proxy for abundance, it is assumed to be so despite the absence of robust data to validate use of CPUE in this way. In some jurisdictions CPUE is supplemented by sparse fishery-independent size and density data. Therefore, there is a  need to review common assumptions, methods and interpretations of CPUE as a primary indicator, and to determine whether inclusion of spatial fishery data could provide a 'global' indicator of stock status for abalone fisheries.

This report examines the potential contribution to fishery assessments by using spatially explicit abalone fishing data. The project utilises spatial data collected by the Tasmanian abalone fishery GPS logger data program, along with catch and effort data from fisher docket returns.  In particular we address the issue of hyperstability, which was the prime motivator of developing the passive GPS and depth data logger program in Tasmania in 2005. We also explore the potential of spatially explicit abalone fishing data to highlight spatio-temporal dynamics of fishing.
