# Acknowledgments {#sec-acknowl .unnumbered}

\pagenumbering{arabic}

This project was supported by funding from the Fisheries Research Development Corporation on behalf of the Australian Government and was co-funded by the Institute of Marine and Antarctic Sciences (IMAS), University of Tasmania. This project received financial support from Natural Resources and Environment Tasmania (NRET), and from the Tasmanian Abalone Council Limited (TACL) to fund local development of GPS and depth data loggers to IMAS specifications. Luisa Forbes managed data logger allocation and retrieval to/from divers for the program from 2019. Luisa Forbes also provided critical support in the development, field testing, and finally deploying the next generation loggers. SciElex has accommodated and facilitated many of our requested changes in the firmware and helped to make this program a success.

# Executive Summary {#sec-ExecSumm .unnumbered}

Capture of high resolution abalone fisheries data through the combination of passive GPS and depth data has been pioneered in Tasmania, with a 12 year time-series of mandatory use of the data logging hardware in Tasmania, covering around 90% of fishing activity. This project has exploited that time-series to address key challenges in assessment of abalone fisheries, particularly the global dilemma of quantifying catch rate hyperstability. The high-resolution spatial fisheries data have multiple applications, including the generation of new spatial performance measures, quantifying the spatial structure of our fisheries, as well as providing insights to the natural dynamics of dive fishery fleets.

## Background

This project is the third in a series of projects aimed at developing the logic and data analysis workflow for electronic high resolution data in abalone fisheries. The first project ([FRDC 2006/029](https://www.frdc.com.au/project/2006-029)) established a database backend/frontend for managing the deployment/retrieval of loggers to/from fishers, basic principals of handling and processing the electronic data stream in R, and structural components of two processed data formats. The second project ([FRDC 2011/201](https://www.frdc.com.au/project/2011-201)) further refined the methods for processing the electronic data streams and examined basic properties of the spatial data (Chapters 5 and 6), as well as exploring a range of analytical applications to maximise the potential of the high-resolution data streams (Chapters 7 to 12).

## Aims/objectives

Among the Australian states with a wild-harvest abalone fishery, Tasmania has the longest time-series of data collected from a GPS and depth data logger program (12 years at the completion of this project). Prior to incorporating this data in Fishery Assessments, there were two specific challenges to be addressed: 1. identify a statistical solution to quantify hyperstability in catch rates, and 2. develop a framework for incorporating spatial data into catch-rate standardisation. This project was focused on these two tasks, in addition to further exploration of questions that might be addressed using the electronic spatial data, in addition to refining our estimates of catch-rates.

There were four primary objectives identified: 1. Characterise the statistical properties, consistency, interpretability and assumptions of spatial and classic indicators of fishery performance. 2. Develop methods for inclusion of fine-scale spatial data in CPUE standardisations. 3. Identify methods for detecting hyperstability in CPUE. 4. Determine feasibility of spatial data based stock status determination in spatially structured fisheries.

## Methodology

This project focused primarily on the dive polygon derived by extracting the 75th percentile isopleth from a bivariate Kernel Utilisation Distribution (KUD) applied to each discrete dive event. The area and maximum linear extent of the KUD polygon were extracted as candidate performance measures, while the centroid of each KUD was used to represent the spatial location of each dive event. The majority of work was focused around these two measures - polygon area, and polygon length. Data from 2012 to 2021 have been utilised in this report, with the most recent years excluded to protect time-sensitive recent fishing data.

Broader consideration of the spatial structure and dynamic of the fishery and the fleet, and possible new approaches, were examined using the Hexgrid product - where each hexagon contains the total catch and effort across all divers for each year in the time-series [see section 6.4 in @mundy2012]. For those unfamiliar with data products derived from the Tasmanian abalone GPS logger program, a detailed description is provided in Chapters 5 and 6 of @mundy2018a. For brevity, the detail of those basic methods and data descriptions are not repeated here.

This project spanned the COVID era, with work conducted through remote collaboration, and when permissible, face to face sessions. The project team was a collaboration between fisheries ecologists, statisticians and fisheries assessment scientists, combining local knowledge of the species, fisheries and data collection program with statistical and assessment expertise. We focused on a small number of regions within the Tasmanian Abalone fishery, particularly the North-West and central east coast as they provided contrasting temporal trends, and magnitude of change over time.

Selection of predictor variables was a key first step, with extensive investigation of environmental variables such as SST (sea surface temperature), wind speed and wave power, along with predictors that represent sub-units of statistical reporting areas. A further consideration once predictors are finalised is whether each term should be considered random or fixed, and the inclusion or not, of interaction terms [@bolker2009; @brown2021; @clark2015; @silk2020]. Most abalone catch-rate data is log-normal, thus the question of whether to model the data as a gamma or log-normal with bias-correction on predicted means was an important consideration. While this made no difference to the outcome, the gamma approach while preferable in terms of simplicity, failed in several of the R packages available for mixed effect linear models.

All statistical analyses were conducted using R [@base] and several packages for mixed-effect models [lme4 @Bates2015; glmmTMB @glmmTMB; sdmTMB @Anderson2022]. This report is produced using Quarto within Rstudio [@quarto].

## Results/key findings

This project makes several important key findings. Firstly that, using passive GPS and depth data logging hardware, we are able to demonstrate that the effort component of the Tasmanian Abalone Fishery Docket returns are comparable to effort values determined from the GPS and depth data loggers. Given that daily catch is accurately weighed and reported, validation of the fishing effort component gives confidence in the long time-series of commercial catch and effort data currently utilised in the Tasmanian Abalone Fishery assessment. We were also able to demonstrate and quantify the existence of hyperstability in catch rate data, and, that hyperstability occurs when the stock is low and declining, but also when the stock is improving. While it has long been assumed that hyperstable catch rates are problematic in abalone fisheries, it has previously been unquantifiable and therefore difficult to address in Harvest Strategies. The current Tasmanian Empirical Harvest Strategy includes an asymmetric control rule as a precautionary approach to account for hyperstable catch rates when stocks are in decline. The findings from this project validate the inclusion of that measure and provide support for ongoing retention of an asymmetric control rule.

This project demonstrates that dive polygon area, rather than dive time, is a much more appropriate measure of effort. Consequently, future utilisation of the GPS program derived spatial fisheries data will utilise area in all calculations of catch rates, rather than as a predictor in the standardisation model. At the commencement of this project, we were intent on exploring how to incorporate spatial performance measure in catch rate standardisations. Other candidate spatial performance measures such as the number of dives per day were less useful, and are likely to have a non-linear relationship with stock abundance.

An exhaustive investigation of the value of including environmental predictors (appendices 13 - 15) in catch rate standardisations found little evidence at the scale of zones to support their inclusion. While sea temperature was not expected to be an important predictor of catch rates, wind speed and wave power were. There was however little direct evidence of an effect of these variables on mean annual catch rates, possibly because of the opportunity on any given day of fishing to find relatively sheltered locations to fish. Thus these two variables are likely to have an upper threshold, beyond which fishing is not practical (or safe) rather than as a direct determinant of catch rate. Further investigation of environmental influences on fleet dynamics is under way as part of a PhD project independent of this project.

Explicit inclusion of dive location in statistical catch rate standardisations appeared to have no material consequence on estimated annual mean catch rate. While spatial heterogeneity in abalone fisheries is well known, it was uncertain as to whether this mattered in the context of calculating catch rates. This finding simplifies the statistical modelling runs, as inclusion of spatial explicit terms either as a spline in a GAMM or as a spatial term in sdmTMB, has very high computing overheads. However as a secondary indicator, examination of the spatial distribution of residuals from spatially explicit Linear Mixed Effect Models provides valuable insights to the spatio-temporal dynamic within a Spatial Assessment Unit (SAU).

Inclusion of a rule-based process to identify distinct fishing grounds was trialled with some success. Abalone fisheries historically have used broad scale reporting areas (Blocks, Spatial Assessment Units, Spatial Management Units, Area). Over the past few decades, the realisation that there is considerable value in reporting at smaller scales has seen all abalone fisheries include finer scale statistical reporting areas, within which fishers must report daily catch and effort. These smaller areas (subblocks, mapcodes, reefcodes) are arbitrarily determined based on local knowledge, but often dissect contiguous rocky reef. An additional benefit of the GPS logger program is the ability to apply spatial clustering methods to identify discrete fishing grounds, resulting in a large number (mostly) of more appropriately bounded, small spatial units to capture structure within larger reporting areas.

## Implications for relevant stakeholders

Development and validation of spatial performance measures from the Tasmanian GPS logger program has only been possible by the foresight of both the Tasmanian Government and the Tasmanian abalone fishery to establish GPS based data collection as a mandatory reporting requirement in 2012. This program, now in its 12th year has underpinned the success of this project. Other states wishing to capitalise on these findings are likely to be able to make use of a GPS data program within a shorter time-period, on the assumption that fishing operations and species are largely similar across states.

For Tasmania, this project provides the confidence to expand the Tasmanian Empirical Harvest Strategy to include catch rates based on area, and when using GPS logger data, to replace subblock terms with cluster ID to account for within SAU structure in catch rate standardisations. There remain challenges in terms of identifying Target reference Points (TRP) and Limit Reference Points (LRP) for catch rates calculated using *area* as the measure of effort. Proxy TRPs and LRPs may be defined by empirical relationships between dive time and dive area, and will be explored further as the time-series expands.

Docket book derived fishing effort for calculation of catch rates will remain a key component of Harvest Strategies across all jurisdictions, in order to capitalise on the long time-series of commercial Docket book data. It is essential that each jurisdiction include a mechanism to account for the presence of hyperstable catch rates in the mechanics of their harvest strategies, as has been done in Tasmania.

## Keywords {#sec-Keywords}

Stock status, Blacklip Abalone, *Haliotis rubra rubra*, Tasmania, GPS, spatial regression, hyperstability, fleet dynamics
